name: Run Bot
on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests numpy pandas yfinance playwright
          playwright install chromium

      - name: Run Bot
        run: python bot.py
